### ISSUE TITLE
Is this all served from one HTTP GET Function?

### ISSUE THREAD

**Issue by cparker4486** [sdras/sample-vue-shop#12]
Hello @sdras !

Just watched your talk today. I've been wanting to learn to use Vue and have been doing some Functions and Logic Apps work so this was right up my alley but by the end of the video I was left asking myself, "When does she start actually using Functions?"

I know you talked about Functions in the beginning, with regards to Stripe, but is that the only place Functions is used? This repo doesn't appear to be ready to be dropped in as a Function app so does that mean it is hosted on a traditional web host?

Thank you!

**Comment by sdras** [comment]
Hi! Thanks for visiting.

I think you might have missed the part when I was talking about the function- it was about half of the total talk. There was a bird's eye view I was using to talk about which section I was focusing on. This repo shows the application- and yes it's hosted on app services. This part is not a serverless function. The serverless function is in another repo, linked up in the readme.

**Comment by cparker4486** [comment]
I kind of put the pieces together after my post. I went into it thinking it was something else. It was worth the watch regardless. Thanks.
