### ISSUE TITLE
Redirect from /women to /dist/women

### ISSUE THREAD

**Issue by daxartio** [sdras/sample-vue-shop#15]

**Comment by sdras** [comment]
I don't think this is necessary, and this issue has no details, so I'm closing it out. If you have more information I would consider reopening.

**Comment by daxartio** [comment]
1. Go to page https://shoppity.azurewebsites.net/men (for example)
1. Click f5 (refresh page)
1. Appeared on page https://shoppity.azurewebsites.net/dist/men/

**Comment by daxartio** [comment]
It`s bug
