### ISSUE TITLE
Improve filterProducts function by using ES6 filter

### ISSUE THREAD

**Issue by afontcu** [sdras/sample-vue-shop#8]
Hi Sarah,

thanks for this repo, it's a great example and I think It'll come in handy soon enough for me :)

I noticed a couple of lines where you could improve the readability of your code by using ES6 functions such as filter, map and reduce.

For example, you could replace the whole filterProducts with a one-liner:

https://github.com/sdras/sample-vue-shop/blob/61bc699140cb329e0f1164a1875bc0f9cb2ddb46/store/index.js#L148

```js
const filterByCategory = (arr, title) => arr.filter(item => item.category === title)

// and then, in your getters:
women: state => filterByCategory(state.products, 'women'),
```

I'd be happy to submit a PR if you think it's worth it.

Again, thanks for your work! 💪

**Comment by sdras** [comment]
Oh great call, I'd totally accept a PR for this. If you don't have the time, I'll refactor. Thanks! 🙌

**Comment by afontcu** [comment]
np i'm on it :) glad to help.

I'll close this and reference it in the PR.

**Comment by sdras** [comment]
dope! thx
